from __future__ import annotations

from pathlib import Path

from .config import BackendConfig, GatewayConfig

PROVIDER_PREFIX: dict[str, str] = {
    "openai": "openai",
    "anthropic": "anthropic",
    "gemini": "gemini",
}


def _yaml_str(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _model_entries(backend: BackendConfig) -> list[str]:
    prefix = PROVIDER_PREFIX.get(backend.name, backend.name)
    lines: list[str] = []
    for model in backend.models:
        lines.append(f"  - model_name: {_yaml_str(model)}")
        lines.append("    litellm_params:")
        lines.append(f"      model: {_yaml_str(f'{prefix}/{model}')}")
        if backend.api_base:
            lines.append(f"      api_base: {_yaml_str(backend.api_base)}")
        lines.append(f"      api_key: {_yaml_str(backend.api_key or 'dummy')}")
    return lines


def render_yaml(cfg: GatewayConfig) -> str:
    lines: list[str] = []
    lines.append("# Generated by llmwiki gateway. Do not edit by hand.")
    lines.append("model_list:")

    backends = list(cfg.backends.values())
    if not backends:
        lines.append("  []")
    else:
        for backend in backends:
            lines.extend(_model_entries(backend))

    lines.append("")
    lines.append("general_settings:")
    lines.append(f"  master_key: {_yaml_str(cfg.master_key)}")

    lines.append("")
    lines.append("litellm_settings:")
    lines.append(f"  request_timeout: {int(cfg.request_timeout)}")
    lines.append("  drop_params: true")

    lines.append("")
    lines.append("# RAG callback added by issue #14")
    lines.append("# callbacks: []")
    lines.append("")
    return "\n".join(lines)


def write_config(cfg: GatewayConfig, out: Path) -> Path:
    out = Path(out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render_yaml(cfg), encoding="utf-8")
    return out
